version: "3.8"

services:
    portfolio.app:
        build:
            context: main
            dockerfile: Dockerfile
        container_name: portfolio.app
        volumes:
            - ./main:/var/www
        ports:
            - 8000:8000
        depends_on:
            - portfolio.db
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret

    portfolio.db:
        image: postgres:15
        container_name: portfolio.db
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - portfolio-data:/var/lib/postgresql/data

volumes:
    portfolio-data:
